version: "3"
services:
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  flower:
    build:
      context: ./worker
      dockerfile: dockerfile.flower
    ports:
      - "5555:5555"

networks:
  dyn_worker_default:
